name: OnCICI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Benchmarking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ [gcc,g++], [clang,clang++] ]
    steps:
    - uses: actions/checkout@v4
    - name: Building
      env:
        CC: ${{ matrix.compiler[0] }}
        CXX: ${{ matrix.compiler[1] }}
      run: |
        mkdir build
        cd build
        cmake ..
        make bench
    - name: Benchmarking
      run: |
        cd build
        bin/bench | tee timings_${{ matrix.compiler[0] }}.txt
    - uses: actions/upload-artifact@v4
      with:
        name: Timings_${{ matrix.compiler[0] }}
        path: build/timings_${{ matrix.compiler[0] }}.txt
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Building
      run: |
        mkdir build
        cd build
        cmake ..
        make tests
    - name: Testing
      run: |
        cd build
        bin/tests
